package motorPH;

public class Task7 {

	public static void main(String[] args) {
		// Practice makes it perfect
		
		String employeeName, birthDate, address, phoneNumber, sss, philHealth, tin, pagIbig, status, position, iSupervisor;
		int employeeNumber, basicSalary, riceSubsidy, pAllowance, cAllowance, grossSemiMR;
		double hourlyRate;
		
		
		employeeNumber = 10001;
		employeeName = "Jose Crisostomo";
		birthDate = "2/14/1988";
		address = "17/85 Stracke Via Suite 042, Poblacion, Las Pinas 4783 Dinagat Islands";
		phoneNumber = "918-621-603";
		sss = "49-1632020-8";
		philHealth = "382189453145";
		tin = "317-674-022-000";
		pagIbig = "441093369646";
		status = "Regular";
		position = "HR Manager";
		iSupervisor = "N/A";
		basicSalary = 62670;
		riceSubsidy = 1500;
		pAllowance = 1000;
		cAllowance = 1000;
		grossSemiMR = 31335;
		hourlyRate = 373.04;
		
		
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);
		
		System.out.println();
		
		employeeNumber = 10002;
		employeeName = "Christian Mata";
		birthDate = "10/21/1987";
		address = "90 O'Keefe Spur Apt. 379, Catigbian 2772 Sulu ";
		phoneNumber = "783-776-744";
		sss = "49-2959312-6";
		philHealth = "824187961962";
		tin = "103-100-522-000";
		pagIbig = "631052853464";
		status = "Regular";
		position = "Account Team Leader";
		iSupervisor = "Romualdez, Fredrick";
		basicSalary = 42975;
		riceSubsidy = 1500;
		pAllowance = 800;
		cAllowance = 800;
		grossSemiMR = 21488;
		hourlyRate = 255.80;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);
		
		System.out.println();
		
		employeeNumber = 10003;
		employeeName = "Brad San Jose";
		birthDate = "3/15/1996";
		address = "99 Strosin Hills, Poblacion, Bislig 5340 Tawi-Tawi";
		phoneNumber = "797-009-261";
		sss = "40-2400714-1";
		philHealth = "239192926939";
		tin = "672-474-690-000";
		pagIbig = "210850209964";
		status = "Regular";
		position = "HR Team Leader";
		iSupervisor = "Crisostomo, Jose";
		basicSalary = 42975;
		riceSubsidy = 1500;
		pAllowance = 800;
		cAllowance = 800;
		grossSemiMR = 21488;
		hourlyRate = 255.80;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);
		
		System.out.println();
		
		employeeNumber = 10004;
		employeeName = "Anthony Salcedo";
		birthDate = "9/14/1993";
		address = "93/54 Shanahan Alley Apt. 183, Santo Tomas 1572 Masbate";
		phoneNumber = "070-766-300";
		sss = "26-9647608-3";
		philHealth = "126445315651";
		tin = "210-805-911-000";
		pagIbig = "218002473454";
		status = "Regular";
		position = "Payroll Manager";
		iSupervisor = "Crisostomo, Jose";
		basicSalary = 60825;
		riceSubsidy = 1500;
		pAllowance = 1000;
		cAllowance = 1000;
		grossSemiMR = 30413;
		hourlyRate = 362.05;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);
		
		System.out.println();
		
		employeeNumber = 10005;
		employeeName = "Alice Romualdez";
		birthDate = "5/14/1992";
		address = "12A/33 Upton Isle Apt. 420, Roxas City 1814 Surigao del Norte";
		phoneNumber = "983-606-799";
		sss = "55-4476527-2";
		philHealth = "545652640232";
		tin = "888-572-294-000";
		pagIbig = "211385556888";
		status = "Regular";
		position = "HR Rank and File";
		iSupervisor = "San Jose, Brad";
		basicSalary = 22500;
		riceSubsidy = 1500;
		pAllowance = 500;
		cAllowance = 500;
		grossSemiMR = 11250;
		hourlyRate = 133.93;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);
		
		System.out.println();
		
		employeeNumber = 10006;
		employeeName = "Rosie Atienza";
		birthDate = "9/24/1948";
		address = "90A Dibbert Terrace Apt. 190, San Lorenzo 6056 Davao del Norte";
		phoneNumber = "266-036-427";
		sss = "41-0644692-3";
		philHealth = "708988234853";
		tin = "604-997-793-000";
		pagIbig = "260107732354";
		status = "Regular";
		position = "HR Rank and File";
		iSupervisor = "San Jose, Brad";
		basicSalary = 22500;
		riceSubsidy = 1500;
		pAllowance = 500;
		cAllowance = 500;
		grossSemiMR = 11250;
		hourlyRate = 133.93;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);
		System.out.println();
		
		employeeNumber = 10007;
		employeeName = "Martha Farala";
		birthDate = "1/11/1942";
		address = "42/25 Sawayn Stream, Ubay 1208 Zamboanga del Norte";
		phoneNumber = "329-034-366";
		sss = "45-5656375-0";
		philHealth = "233693897247";
		tin = "210-835-851-000";
		pagIbig = "631130283546";
		status = "Regular";
		position = "Payroll Rank and File";
		iSupervisor = "Farala, Martha";
		basicSalary = 24000;
		riceSubsidy = 1500;
		pAllowance = 500;
		cAllowance = 500;
		grossSemiMR = 12000;
		hourlyRate = 142.86;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);

		System.out.println();
		
		employeeNumber = 10008;
		employeeName = "Leila Martinez";
		birthDate = "7/11/1970";
		address = "37/46 Kulas Roads, Maragondon 0962 Quirino";
		phoneNumber = "877-110-749";
		sss = "27-2090996-4";
		philHealth = "515741057496";
		tin = "275-792-513-000";
		pagIbig = "101205445886";
		status = "Regular";
		position = "Payroll Rank and File";
		iSupervisor = "Farala, Martha";
		basicSalary = 24000;
		riceSubsidy = 1500;
		pAllowance = 500;
		cAllowance = 500;
		grossSemiMR = 12000;
		hourlyRate = 142.86;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);
		
		System.out.println();
		
		employeeNumber = 10009;
		employeeName = "Allison San Jose";
		birthDate = "6/24/1986";
		address = "08 Grant Drive Suite 406, Poblacion, Iloilo City 9186 La Union";
		phoneNumber = "179-075-129";
		sss = "45-3251383-0";
		philHealth = "745148459521";
		tin = "121-203-336-000";
		pagIbig = "114901859343";
		status = "Regular";
		position = "Account Rank and File";
		iSupervisor = "Mata, Christian";
		basicSalary = 22500;
		riceSubsidy = 1500;
		pAllowance = 500;
		cAllowance = 500;
		grossSemiMR = 11250;
		hourlyRate = 133.93;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);
		
		System.out.println();
		
		employeeNumber = 10010;
		employeeName = "Cydney Rosario";
		birthDate = "10/6/1996";
		address = "93A/21 Berge Points, Tapaz 2180 Quezon";
		phoneNumber = "868-819-912";
		sss = "49-1629900-2";
		philHealth = "579253435499";
		tin = "122-244-511-000";
		pagIbig = "265104358643";
		status = "Regular";
		position = "Account Rank and File";
		iSupervisor = "Mata, Christian";
		basicSalary = 22500;
		riceSubsidy = 1500;
		pAllowance = 500;
		cAllowance = 500;
		grossSemiMR = 11250;
		hourlyRate = 133.93;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);
		
		System.out.println();
		
		employeeNumber = 10011;
		employeeName = "Josie Lopez";
		birthDate = "1/14/1937";
		address = "49 Springs Apt. 266, Poblacion, Taguig 3200 Occidental Mindoro";
		phoneNumber = "478-355-427";
		sss = "44-8563448-3";
		philHealth = "431709011012";
		tin = "218-489-737-000";
		pagIbig = "113071293354";
		status = "Regular";
		position = "Payroll Team Leader";
		iSupervisor = "Salcedo, Anthony";
		basicSalary = 38475;
		riceSubsidy = 1500;
		pAllowance = 800;
		cAllowance = 800;
		grossSemiMR = 19238;
		hourlyRate = 229.02;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);
		
		System.out.println();
		
		employeeNumber = 10012;
		employeeName = "Selena De Leon";
		birthDate = "2/20/1945";
		address = "89A Armstrong Trace, Compostela 7874 Maguindanao";
		phoneNumber = "975-432-139";
		sss = "27-2090208-8";
		philHealth = "587272469938";
		tin = "482-259-498-000";
		pagIbig = "719007608464";
		status = "Regular";
		position = "Account Team Leader";
		iSupervisor = "Romualdez, Fredrick";
		basicSalary = 41850;
		riceSubsidy = 1500;
		pAllowance = 800;
		cAllowance = 800;
		grossSemiMR = 20925;
		hourlyRate = 249.11;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);
		
		System.out.println();
		
		employeeNumber = 10013;
		employeeName = "Fredrick Romualdez";
		birthDate = "3/10/1985";
		address = "22A/52 Lubowitz Meadows, Pililla 4895 Zambales";
		phoneNumber = "023-079-009";
		sss = "26-8768374-1";
		philHealth = "308366860059";
		tin = "598-065-761-000";
		pagIbig = "223057707853";
		status = "Regular";
		position = "Account Manager";
		iSupervisor = "Crisostomo, Jose";
		basicSalary = 63500;
		riceSubsidy = 1500;
		pAllowance = 1000;
		cAllowance = 1000;
		grossSemiMR = 31750;
		hourlyRate = 377.98;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);
		
		System.out.println();
		
		employeeNumber = 10014;
		employeeName = "Mark Bautista";
		birthDate = "2/12/1961";
		address = "65 Murphy Center Suite 094, Poblacion, Palayan 5636 Quirino";
		phoneNumber = "683-725-348";
		sss = "49-1647342-5";
		philHealth = "399665157135";
		tin = "273-970-941-000";
		pagIbig = "260054585575";
		status = "Regular";
		position = "Account Rank and File";
		iSupervisor = "Mata, Christian";
		basicSalary = 23250;
		riceSubsidy = 1500;
		pAllowance = 500;
		cAllowance = 500;
		grossSemiMR = 11625;
		hourlyRate = 138.39;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);
		
		System.out.println();
		
		employeeNumber = 10015;
		employeeName = "Darlene Lazaro";
		birthDate = "11/25/1985";
		address = "47A/94 Larkin Plaza Apt. 179, Poblacion, Caloocan 2751 Quirino";
		phoneNumber = "740-721-558";
		sss = "45-5617168-2";
		philHealth = "606386917510";
		tin = "354-650-951-000";
		pagIbig = "104907708845";
		status = "Probationary";
		position = "Account Rank and File";
		iSupervisor = "Mata, Christian";
		basicSalary = 23250;
		riceSubsidy = 0;
		pAllowance = 0;
		cAllowance = 0;
		grossSemiMR = 11625;
		hourlyRate = 138.39;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);
		
		System.out.println();
		
		employeeNumber = 10016;
		employeeName = "Kolby Delos Santos";
		birthDate = "2/26/1980";
		address = "06A Gulgowski Extensions, Bongabon 6085 Zamboanga del Sur";
		phoneNumber = "739-443-033";
		sss = "52-0109570-6";
		philHealth = "357451271274";
		tin = "187-500-345-000";
		pagIbig = "113017988667";
		status = "Probationary";
		position = "Account Rank and File";
		iSupervisor = "Mata, Christian";
		basicSalary = 24000;
		riceSubsidy = 0;
		pAllowance = 0;
		cAllowance = 0;
		grossSemiMR = 12000;
		hourlyRate = 142.86;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);
		
		System.out.println();
		
		employeeNumber = 10017;
		employeeName = "Vella Santos";
		birthDate = "12/31/1983";
		address = "99A Padberg Spring, Poblacion, Mabalacat 3959 Lanao del Sur";
		phoneNumber = "955-879-269";
		sss = "52-9883524-3";
		philHealth = "548670482885";
		tin = "101-558-994-000";
		pagIbig = "360028104576";
		status = "Probationary";
		position = "Account Rank and File";
		iSupervisor = "Mata, Christian";
		basicSalary = 22500;
		riceSubsidy = 0;
		pAllowance = 0;
		cAllowance = 0;
		grossSemiMR = 11250;
		hourlyRate = 133.93;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);
		
		System.out.println();
		
		employeeNumber = 10018;
		employeeName = "Tomas Del Rosario";
		birthDate = "12/18/1978";
		address = "80A/48 Ledner Ridges, Poblacion, Kabankalan 8870 Marinduque";
		phoneNumber = "882-550-989";
		sss = "45-5866331-6";
		philHealth = "953901539995";
		tin = "560-735-732-000";
		pagIbig = "913108649964";
		status = "Probationary";
		position = "Account Rank and File";
		iSupervisor = "Mata, Christian";
		basicSalary = 22500;
		riceSubsidy = 0;
		pAllowance = 0;
		cAllowance = 0;
		grossSemiMR = 11250;
		hourlyRate = 133.93;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);
		
		System.out.println();
		
		employeeNumber = 10019;
		employeeName = "Jacklyn Tolentino";
		birthDate = "5/19/1944";
		address = "96/48 Watsica Flats Suite 734, Poblacion, Malolos 1844 Ifugao";
		phoneNumber = "675-757-366";
		sss = "47-1692793-0";
		philHealth = "753800654114";
		tin = "841-177-857-000";
		pagIbig = "210546661243";
		status = "Probationary";
		position = "Account Rank and File";
		iSupervisor = "De Leon, Selena";
		basicSalary = 24000;
		riceSubsidy = 0;
		pAllowance = 0;
		cAllowance = 0;
		grossSemiMR = 12000;
		hourlyRate = 142.86;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);
		
		System.out.println();
		
		employeeNumber = 10020;
		employeeName = "Percival Gutierrez";
		birthDate = "12/18/1970";
		address = "58A Wilderman Walks, Poblacion, Digos 5822 Davao del Sur";
		phoneNumber = "512-899-876";
		sss = "40-9504657-8";
		philHealth = "797639382265";
		tin = "502-995-671-000";
		pagIbig = "210897095686";
		status = "Probationary";
		position = "Account Rank and File";
		iSupervisor = "De Leon, Selena";
		basicSalary = 24750;
		riceSubsidy = 0;
		pAllowance = 0;
		cAllowance = 0;
		grossSemiMR = 12375;
		hourlyRate = 147.32;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);
		
		System.out.println();
		
		employeeNumber = 10021;
		employeeName = "Garfield Manalaysay";
		birthDate = "8/28/1966";
		address = "60 Goyette Valley Suite 219, Poblacion, Tabuk 3159 Lanao del Sur";
		phoneNumber = "948-628-136";
		sss = "45-3298166-4";
		philHealth = "810909286264";
		tin = "336-676-445-000";
		pagIbig = "211274476563";
		status = "Probationary";
		position = "Account Rank and File";
		iSupervisor = "De Leon, Selena";
		basicSalary = 24750;
		riceSubsidy = 0;
		pAllowance = 0;
		cAllowance = 0;
		grossSemiMR = 12375;
		hourlyRate = 147.32;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);
		
		System.out.println();
		
		employeeNumber = 10022;
		employeeName = "Lizeth Villegas";
		birthDate = "12/12/1981";
		address = "66/77 Mann Views, Luisiana 1263 Dinagat Islands";
		phoneNumber = "332-372-215";
		sss = "40-2400719-4";
		philHealth = "934389652994";
		tin = "210-395-397-000";
		pagIbig = "122238077997";
		status = "Probationary";
		position = "Account Rank and File";
		iSupervisor = "De Leon, Selena";
		basicSalary = 24000;
		riceSubsidy = 0;
		pAllowance = 0;
		cAllowance = 0;
		grossSemiMR = 12000;
		hourlyRate = 142.86;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);
		
		System.out.println();
		
		employeeNumber = 10023;
		employeeName = "Carol Ramos";
		birthDate = "8/20/1978";
		address = "72/70 Stamm Spurs, Bustos 4550 Iloilo";
		phoneNumber = "250-700-389";
		sss = "60-1152206-4";
		philHealth = "351830469744";
		tin = "395-032-717-000";
		pagIbig = "212141893454";
		status = "Probationary";
		position = "Account Rank and File";
		iSupervisor = "De Leon, Selena";
		basicSalary = 22500;
		riceSubsidy = 0;
		pAllowance = 0;
		cAllowance = 0;
		grossSemiMR = 11250;
		hourlyRate = 133.93;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);

		System.out.println();
		
		employeeNumber = 10024;
		employeeName = "Emelia Maceda";
		birthDate = "4/14/1963";
		address = "50A/83 Bahringer Oval Suite 145, Kiamba 7688 Nueva Ecija";
		phoneNumber = "973-358-041"; 
		sss = "54-1331005-0";
		philHealth = "465087894112";
		tin = "215-973-013-000";
		pagIbig = "515012579765";
		status = "Probationary";
		position = "Account Rank and File";
		iSupervisor = "De Leon, Selena";
		basicSalary = 22500;
		riceSubsidy = 0;
		pAllowance = 0;
		cAllowance = 0;
		grossSemiMR = 11250;
		hourlyRate = 133.93;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);

		System.out.println();
		
		employeeNumber = 10025;
		employeeName = "Delia Aguilar";
		birthDate = "1/27/1939";
		address = "95 Cremin Junction, Surallah 2809 Cotabato";
		phoneNumber = "529-705-439";
		sss = "52-1859253-1";
		philHealth = "136451303068";
		tin = "599-312-588-000";
		pagIbig = "110018813465";
		status = "Probationary";
		position = "Account Rank and File";
		iSupervisor = "De Leon, Selena";
		basicSalary = 22500;
		riceSubsidy = 0;
		pAllowance = 0;
		cAllowance = 0;
		grossSemiMR = 11250;
		hourlyRate = 133.93;
	
		System.out.println("Employee Number          : "+employeeNumber);
		System.out.println("Employee Name            : "+employeeName);
		System.out.println("Birth Date               : "+birthDate);
		System.out.println("Address                  : "+address);
		System.out.println("Phone Number             : "+phoneNumber);
		System.out.println("SSS #                    : "+sss);
		System.out.println("PhilHealth #             : "+philHealth);
		System.out.println("Tin #                    : "+tin);
		System.out.println("Pag-Ibig #               : "+pagIbig);
		System.out.println("Status                   : "+status);
		System.out.println("Position                 : "+position);
		System.out.println("Immediate Supervisor     : "+iSupervisor);
		System.out.println("Basic Salary             : "+basicSalary);
		System.out.println("Rice Subsidy             : "+riceSubsidy);
		System.out.println("Phone Allowance          : "+pAllowance);
		System.out.println("Clothing Allowance       : "+cAllowance);
		System.out.println("Gross Semi-monthly Rate  : "+grossSemiMR);
		System.out.println("Hourly Rate              : "+hourlyRate);

		

	}

}
